# fly.toml app configuration file generated for microbiome-tracker on 2026-03-07T15:37:36-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'microbiome-tracker'
primary_region = 'lax'

[build]

[deploy]
  strategy = 'immediate'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
